### PR TITLE
Fix incorrect calculation of duration for VBR encoded MP3s

### PR DESCRIPTION
**Pull request by devsnd**

### CODE REVIEW

**Comment by mathiascode** [comment]
There are still some odd CBR mp3s that show similar symptoms (duration cut in half), which would be interesting to investigate, but this fix works for the majority of files.
https://github.com/JamesHeinrich/getID3-testfiles/tree/master/mp3/LAME%20CBR

**Comment by devsnd** [comment]
Hm, I'd need to make a few more tests with many files to see how this affects the calculations. I'm hesitant to merge this because I find it weird that removing the division by channels should yield correct results? The unit-tests are actually to few to establish a ground truth on all the different files out there. I'll try to run the different implementations against my music-collection to see what happens then :question:

**Comment by mathiascode** [comment]
IIRC, the changes worked correctly on the files I tested, but I wasn't fully confident in applying the fix in this location of the code. You could try this collection, it contains all kinds of uncommon files: https://github.com/JamesHeinrich/getID3-testfiles

There were a few odd MP3s in that collection that still reported an incorrect bitrate despite this fix, but that might be a different issue.

**Comment by devsnd** [comment]
Oh wow, this repo you linked is a goldmine! I'll add an extended test-suite that will incorporate this corpus of data...!

**Comment by devsnd** [comment]
I've tested your changes and applied them to the master branch. I was too lazy to rebase, so I just copy pasted from the PR.

**Pull request closed without merging**
