### PR TITLE
Add description fields

### PR DESCRIPTION
**Pull request by snowskeleton**
I have some audio files with the commented out fields that I verified as working.

### CODE REVIEW

**Comment by mathiascode** [comment]
I wonder if we should map these fields to `comment` instead. What's the difference between description and comment in mp4 files?

**Comment by snowskeleton** [comment]
I've primarily worked with Audible files, where `\xa9cmt` is the primary description field, with `\xa9des` as overflow after ~120 characters (otherwise absent).

An audiobook from a different source only uses the `desc` atom for the full description, with both `\xa9des` and `\xa9cmt` atoms empty/null. I can't find any official documentation about them being mutually exclusive, though, which is why I opted to give it a separate field.

Is there something else the `\xa9des` field gets used for, in your experience?  If not, it would definitely be nice to have them both point to `extra.description`.

**Comment by mathiascode** [comment]
It seems like `desc` is used for descriptions in most cases, while `\xa9des` isn't as common. I would map both of them to `extra.description`.

Do you have any files with the `\xa9des` field, and a short, preferably generic description? We need one for the test suite.

Here's a generic file with the `desc` field:
[desc.zip](https://github.com/devsnd/tinytag/files/10373643/desc.zip)

**Comment by mathiascode** [comment]
Thanks, I'll see if I can change the description.

> Is there a typical strategy you suggest for creating this sort of sample files?

It depends. I usually try to create a small file containing silence, using e.g. Audacity, and add tags with Kid3 or another tag editor. If it's a rare file that can't be replicated with modern tools, I use the `truncate` command to remove audio data (as long as tags are located at the beginning of the file, which is typically the case).

**Comment by snowskeleton** [comment]
I used the first `desc` sample you provided. The other one seemed to have some extra data in it for some reason.

I made an educated guess on name formatting. Lemme know if they should be named differently.

**Comment by mathiascode** [comment]
I made my second desc sample slightly longer, so you get some bitrate/duration/sample rate data from it as well.

Can you add the files to the test_all.py file, under the M4A section? Once that's done, this PR looks good to me.

**Comment by snowskeleton** [comment]
Entries added, and tests passing. I also swapped in the more recent `desc` sample; I should have know it was different for a reason :)

**Review by mathiascode — APPROVED** [review]

**Comment by mathiascode** [comment]
Thanks!

**Pull request merged**
