### PR TITLE
Add albumartist.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Album artist field contains the name of the artist who did the compilation. For example in 

LateNightTales: Franz Ferdinand
http://musicbrainz.org/release/c44540af-0279-4fcb-9d37-5e331c614db3

`Franz Ferdinand` is always the album artist and each song has its own artist.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Hey @devsnd how can I help to merge this and cut a release?

**Comment by devsnd** [comment]
Hey Giorgos,

thank you very much for your pull request! I however cannot merge it, because you have changed one of the test files erroneously:

You have added ID3v2 tags to the file ```id3v1-latin1.mp3```.

Could you please make another pull request just with the code changes (based off of the current master branch)? I will take care of the test files then.

**Comment by devsnd** [comment]
Hey Giorgos,

I had a look in the ID3 "specs" and it seems there is no such thing as an albumartist.

See: http://id3.org/id3v2.4.0-frames

Quote:

    ...
    lots of shenanigans
    ...
    4.2.2 TPE1 Lead performer(s)/Soloist(s)
    4.2.2 TPE2 Band/orchestra/accompaniment
    4.2.2 TPE3 Conductor/performer refinement
    4.2.2 TPE4 Interpreted, remixed, or otherwise modified by
    ...
    many more silly things
    ...

So I'm not really sure if I want all that stuff inside tinytag, because afterwards tinytag would not be as tiny anymore.

So please convince me that ```TPE2``` (and ```TP2```) are the defacto standard as album artist for compilations and not just any or all of these ```TPE*``` tags!

**Comment by glogiotatidis** [comment]
I get your concerns and indeed there's no official field for albumartist. I'm using [beets](https://github.com/sampsyo/beets/) for managing my collection and other tag editors i've tried like easytag and mp3tag are all repurposing tpe2 for albumartist since there's a genuine need for the field. Without me having a deep knowledge in the field I understand that TPE2 has become the unofficial but de facto field for this information. 

 I'm kinda in need for this field because I'm producing SVGs for coverart and that's how I ended up pull requesting against tinytag. 

If 're interested I'm happy to re-pull request.

**Pull request closed without merging**
