### PR TITLE
Add support for ISRC data

### PR DESCRIPTION
**Pull request by aw-was-here**

### CODE REVIEW

**Comment by devsnd** [comment]
Hey Allen!

Once again, thanks a lot for your PR! I will make a small change though: I will add the `isrc` to the `extra` fields. The idea is that the default fields that tinytag returns will work for most file formats, while the fields in the `extra` `dict` will contain information that might be specific to even just a single file format. In this way I can make sure that the basic scope of tinytag isn't ever increasing, especially for newcomers and first-time-users, I want it to be dead-simple.

Anyway, thanks again for your work, its really appreciated! Have a virtual cookie for your efforts! :cookie:

**Comment by devsnd** [comment]
https://github.com/devsnd/tinytag/commit/752aa4c521f42c8cb710db640ab76ce10d4a3d01

You can now access the `irsc` using `tag.extra.get('isrc')` instead of `tag.isrc`.

**Comment by devsnd** [comment]
Hey Allen,

Thanks again for all your changes. I saw that I didn't release a new version of tinytag in a long while, so I gave myself a kick in the butt and released version 1.6.0 with all your changes now. Have a nice weekend!

**Comment by aw-was-here** [comment]
Thanks!

FWIW, isrc I think is actually supported by most of the formats but I didn't get around to finishing up the support. haha. Sorry.

**Pull request merged**
